### ISSUE TITLE
[feature request] subdomain for karpenter

### ISSUE THREAD

**Issue by flavono123** [cncf/devstats#90]
afaik, karpenter is now one of graduated project of cncf, but no dashboard in devstats:

https://aws.amazon.com/ko/blogs/containers/karpenter-graduates-to-beta/
https://www.cncf.io/blog/2024/11/06/karpenter-v1-0-0-beta/#:~:text=Beyond%20scaling.%20Karpenter%20is%20more%20than%20an,cases%20by%20pairing%20with%20other%20CNCF%20tools

**Comment by lukaszgryglicki** [comment]
Sorry, but this is not related to DevStats.
I don't see that project as CNCF project anywhere in CNCF other repos - DevStats syncs with `cncf/landscape`, `cncf/toc` and `cncf/sandbox`:
```
root@darkstar:~/go/src/github.com/cncf# find.sh ./toc '*' 'karpenter'
root@darkstar:~/go/src/github.com/cncf# find.sh ./sandbox/ '*' 'karpenter'
root@darkstar:~/go/src/github.com/cncf# find.sh ./landscape/ '*' 'karpenter'
./landscape/landscape.yml:9935:            name: Karpenter
./landscape/landscape.yml:9936:            description: Karpenter is a Kubernetes Node Autoscaler built for flexibility, performance, and simplicity.
./landscape/landscape.yml:9937:            repo_url: https://github.com/kubernetes-sigs/karpenter
./landscape/landscape.yml:9938:            logo: karpenter.svg
./landscape/landscape.yml:9940:            homepage_url: https://karpenter.sh
```

This is the `landscape` entry - it is not even marked as a CNCF project:
```
          - item:
            name: Karpenter
            description: Karpenter is a Kubernetes Node Autoscaler built for flexibility, performance, and simplicity.
            repo_url: https://github.com/kubernetes-sigs/karpenter
            logo: karpenter.svg
            unnamed_organization: true
            homepage_url: https://karpenter.sh
```

On the project [website](https://karpenter.sh/) I don't see any mention about CNCF.
